# Indexado, Slicing y operaciones básicas

Vamos a explorar más a fondo la diferentes formas que tenemos de acceder y operar con componentes de un array multidimensional.

In [1]:
import numpy as np

---
## Indexado y *slicing* 

Otra de las características más interesantes de numpy es la gran flexibilidad para acceder a las componentes de un array, o a un subconjunto del mismo. Vamos a ver a continuación algunos ejemplos básicos.

**Arrays unidimensonales**

Para arrays unidimensionales, el acceso es muy parecido al de listas. Por ejemplo, acceso a las componentes:

In [2]:
C = np.arange(10)*2
C

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [3]:
C[5]

10

La operación de *slicing* en arrays es similar a la de listas. Por ejemplo:

In [4]:
C[5:8]

array([10, 12, 14])

Sin embargo, hay una diferencia fundamental: en general en python, el slicing siempre crea *una copia* de la secuencia original (aunque no de los elementos) a la hora de hacer asignaciones. En numpy, el *slicing* es una *vista* de array original. Esto tiene como consecuencia que **las modificaciones que se realicen sobre dicha vista se están realizando sobre el array original**. Por ejemplo:   

In [5]:
C[5:8] = 12
C

array([ 0,  2,  4,  6,  8, 12, 12, 12, 16, 18])

Y además hay que tener en cuenta que cualquier referencia a una vista es en realidad una referencia a los datos originales, y que las modificaciones que se realicen a través de esa referencia, se realizarán igualmente sobre el original.

Veámos esto con el siguiente ejemplo:

In [8]:
# C_slice referencia a las componenentes 5, 6 y 7 del array C.
C_slice = C[5:8]
C_slice

array([12, 12, 12])

Modificamos la componente 1 de `C_slice`:

In [9]:
C_slice[1] = 12345
C_slice

array([   12, 12345,    12])

Pero la componente 1 de `C_slice` es en realidad la componente 6 de `C`, así que `C` ha cambiado:

In [10]:
C

array([    0,     2,     4,     6,     8,    12, 12345,    12,    16,
          18])

Podemos incluso cambiar toda la subsecuencia, cambiando así es parte del array original:

In [11]:
C_slice[:] = 64
C

array([ 0,  2,  4,  6,  8, 64, 64, 64, 16, 18])

Nótese la diferencia con las listas de python, en las que `l[:]` es la manera estándar de crear una *copia* de una lista `l`. En el caso de *numpy*, si se quiere realizar una copia, se ha de usar el método `copy` (por ejemplo, `C.copy()`).

**Arrays de más dimensiones**

El acceso a los componentes de arrays de dos o más dimensiones es similar, aunque la casuística es más variada.

Cuando accedemos con un único índice, estamos accediendo al correspondiente subarray de esa posición. Por ejemplo, en array de dos dimensiones, con 3 filas y 3 columnas, la posición 2 es la tercera fila:

In [15]:
C2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
C2d[2]

array([7, 8, 9])

De esta manera, recursivamente, podríamos acceder a los componentes individuales de una array de cualquier dimensión. En el ejemplo anterior, el elemento de la primera fila y la tercera columna sería:

In [13]:
C2d[0][2]

3

Normalmente no se suele usar la notación anterior para acceder a los elementos individuales, sino que se usa un único corchete con los índices separados por comas: Lo siguiente es equivalente:

In [14]:
C2d[0, 2]

3

Veamos más ejemplos de acceso y modificación en arrays multidimensionales, en este caso con tres dimensiones.

In [16]:
C3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
C3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

Accediendo a la posición 0 obtenemos el correspondiente subarray de dos dimensiones:

In [17]:
C3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

Similar a la función `enumerate` de Python, tenemos la función `np.ndenumearte` para iterar con los elementos del array y su índice

In [ ]:
[i for i in np.ndenumerate(C3d)]

[((0, 0, 0), 1),
 ((0, 0, 1), 2),
 ((0, 0, 2), 3),
 ((0, 1, 0), 4),
 ((0, 1, 1), 5),
 ((0, 1, 2), 6),
 ((1, 0, 0), 7),
 ((1, 0, 1), 8),
 ((1, 0, 2), 9),
 ((1, 1, 0), 10),
 ((1, 1, 1), 11),
 ((1, 1, 2), 12)]

Vamos a guardar una copia de de ese subarray y lo modificamos en el original con el número `42` en todas las posiciones:

In [18]:
old_values = C3d[0].copy()
C3d[0] = 42
C3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

Y ahora reestablecemos los valores originales:

In [19]:
C3d[0] = old_values
C3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

:::{exercise}
:label: introduction-numpy-indexing

Devuelve el número 813 indexando el array `np.arange(2100).reshape((25, 6, 7, 2))`. 

:::

#### Indexado usando *slices*

In [ ]:
C2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Los *slicings* en arrays multidimensionales se hacen a lo largo de los correspondientes ejes. Por ejemplo, en un array bidimensional, lo haríamos sobre la secuencia de filas. 

In [ ]:
C2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

Pero también podríamos hacerlo en ambos ejes. Por ejemplo para obtener el subarray hasta la segunda fila y a partir de la primera columna:

In [ ]:
C2d[:2, 1:]

array([[2, 3],
       [5, 6]])

Si en alguno de los ejes se usa un índice individual, entonces se pierde una de las dimensiones:

In [ ]:
C2d[1, :2]

array([4, 5])

Nótese la diferencia con la operación `C2d[1:2,:2]`. Puede parecer que el resultado ha de ser el mismo, pero si se usa slicing en ambos ejes se mantiene el número de dimensiones:

In [ ]:
C2d[1:2,:2]

array([[4, 5]])

Más ejemplos:

In [ ]:
C2d[:2, 2]

array([3, 6])

In [ ]:
C2d[:, :1]

array([[1],
       [4],
       [7]])

Como hemos visto más arriba, podemos usar *slicing* para asignar valores a las componentes de un array. Por ejemplo

In [ ]:
C2d[:2, 1:] = 0
C2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

:::{exercise}
:label: index-slicing-3x4x2

Crea un array tridimensional de dimensiones $(3, 4, 2)$ y obtén el subarray indicada en la figura 
![picture](https://drive.google.com/uc?id=1HEtbq_Y1YVh6jscdHEhYYz-iM5FNMyJP)

:::

### Indexado con booleanos

Los arrays de booleanos se pueden usar en numpy como una forma de indexado para seleccionar determinadas componenetes en una serie de ejes. 

Veamos el siguiente ejemplo:

In [ ]:
nombres = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [ ]:
data = np.random.randn(7, 4)
data

array([[ 0.0929,  0.2817,  0.769 ,  1.2464],
       [ 1.0072, -1.2962,  0.275 ,  0.2289],
       [ 1.3529,  0.8864, -2.0016, -0.3718],
       [ 1.669 , -0.4386, -0.5397,  0.477 ],
       [ 3.2489, -1.0212, -0.5771,  0.1241],
       [ 0.3026,  0.5238,  0.0009,  1.3438],
       [-0.7135, -0.8312, -2.3702, -1.8608]])

Podríamos interpretar que cada fila del array `data` son datos asociados a las correspondientes personas del array `nombres`. Si ahora queremos quedarnos por ejemplos con las filas correspondientes a Bob, podemos usar indexado booleano de la siguiente manera:

El array de booleanos que vamos a usar será:

In [ ]:
nombres == 'Bob'

array([ True, False, False,  True, False, False, False])

Y el indexado con ese array, en el eje de las filas, nos dará el subarray de las filas correspondientes a Bob:

In [ ]:
data[nombres == 'Bob']

array([[ 0.0929,  0.2817,  0.769 ,  1.2464],
       [ 1.669 , -0.4386, -0.5397,  0.477 ]])

Podemos mezclar indexado booleano con índices concretos o con slicing en distintos ejes:

In [ ]:
data[nombres == 'Bob', 2:]

array([[ 0.769 ,  1.2464],
       [-0.5397,  0.477 ]])

In [ ]:
data[nombres == 'Bob', 3]

array([1.2464, 0.477 ])

Para usar el indexado complementario (en el ejemplo, las filas correspondientes a las personas que no son Bob), podríamos usar el array de booleanos `nombres != 'Bob'`. Sin embargo, es más habitual usar el operador `~`:

In [ ]:
data[~(nombres == 'Bob')]

array([[ 1.0072, -1.2962,  0.275 ,  0.2289],
       [ 1.3529,  0.8864, -2.0016, -0.3718],
       [ 3.2489, -1.0212, -0.5771,  0.1241],
       [ 0.3026,  0.5238,  0.0009,  1.3438],
       [-0.7135, -0.8312, -2.3702, -1.8608]])

Incluso podemos jugar con otros operadores booleanos como `&` (and) y `|` (or), para construir indexados booleanos que combinan condiciones. 

Por ejemplo, para obtener las filas correspondiente a Bob o a Will:

In [ ]:
mask = (nombres == 'Bob') | (nombres == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [ ]:
data[mask]

array([[ 0.0929,  0.2817,  0.769 ,  1.2464],
       [ 1.3529,  0.8864, -2.0016, -0.3718],
       [ 1.669 , -0.4386, -0.5397,  0.477 ],
       [ 3.2489, -1.0212, -0.5771,  0.1241]])

Y como en los anteriores indexados, podemos usar el indexado booleano para modificar componentes de los arrays. Lo siguiente pone a 0 todos los componentes neativos de `data`:

In [ ]:
data<0

array([[False, False, False, False],
       [False,  True, False, False],
       [False, False,  True,  True],
       [False,  True,  True, False],
       [False,  True,  True, False],
       [False, False, False, False],
       [ True,  True,  True,  True]])

In [ ]:
data[data < 0] = 0
data

array([[0.0929, 0.2817, 0.769 , 1.2464],
       [1.0072, 0.    , 0.275 , 0.2289],
       [1.3529, 0.8864, 0.    , 0.    ],
       [1.669 , 0.    , 0.    , 0.477 ],
       [3.2489, 0.    , 0.    , 0.1241],
       [0.3026, 0.5238, 0.0009, 1.3438],
       [0.    , 0.    , 0.    , 0.    ]])

Obsérvese que ahora `data<0` es un array de booleanos bidimensional con la misma estructura que el propio `data` y que por tanto tanto estamos haciendo indexado booleano sobre ambos ejes. 

Podríamos incluso fijar un valor a filas completas, usando indexado por un booleano unidimensional:

In [ ]:
data[~(nombres == 'Joe')] = 7
data

array([[7.    , 7.    , 7.    , 7.    ],
       [1.0072, 0.    , 0.275 , 0.2289],
       [7.    , 7.    , 7.    , 7.    ],
       [7.    , 7.    , 7.    , 7.    ],
       [7.    , 7.    , 7.    , 7.    ],
       [0.3026, 0.5238, 0.0009, 1.3438],
       [0.    , 0.    , 0.    , 0.    ]])

---
## Trasposición de arrays y producto matricial

El método `T` obtiene el array traspuesto de uno dado:

In [ ]:
D = np.arange(15).reshape((3, 5))
D

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
D.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [ ]:
D

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

En el cálculo matricial será de mucha utilidad el método `np.dot` de numpy, que sirve tanto para calcular el producto escalar como el producto matricial. Veamos varios usos: 

In [ ]:
E = np.random.randn(6, 3)
E

array([[-0.8608,  0.5601, -1.2659],
       [ 0.1198, -1.0635,  0.3329],
       [-2.3594, -0.1995, -1.542 ],
       [-0.9707, -1.307 ,  0.2863],
       [ 0.378 , -0.7539,  0.3313],
       [ 1.3497,  0.0699,  0.2467]])

Ejemplos de producto escalar:

In [ ]:
np.dot(E[:,0],E[:,1]) # producto escalar de dos columnas

0.9393581459889597

In [ ]:
np.dot(E[2],E[4]) # producto escalar de dos filas

-1.252231064146922

In [ ]:
np.dot(E.T, E[:,0]) # producto de una matriz por un vector

array([9.2291, 0.9394, 4.948 ])

In [ ]:
np.dot(E.T,E)   # producto de dos matrices

array([[ 9.2291,  0.9394,  4.948 ],
       [ 0.9394,  3.7662, -1.3622],
       [ 4.948 , -1.3622,  4.3437]])

In [ ]:
np.dot(E,E.T)   # producto de dos matrices

array([[ 2.6573, -1.1203,  3.8712, -0.2591, -1.167 , -1.4349],
       [-1.1203,  1.2562, -0.5838,  1.369 ,  0.9573,  0.1695],
       [ 3.8712, -0.5838,  7.9844,  2.1096, -1.2522, -3.5789],
       [-0.2591,  1.369 ,  2.1096,  2.7327,  0.7133, -1.3309],
       [-1.167 ,  0.9573, -1.2522,  0.7133,  0.821 ,  0.5392],
       [-1.4349,  0.1695, -3.5789, -1.3309,  0.5392,  1.8875]])

In [ ]:
np.dot(E.T, E[:,:1]) # producto de dos matrices

array([[9.2291],
       [0.9394],
       [4.948 ]])

## Funciones universales sobre arrays (componente a componente)

En este contexto, una función universal (o *ufunc*) es una función que actúa sobre cada componente de un array o arrays de numpy. Estas funciones son muy eficientes y se denominan *vectorizadas*. Por ejemplo:   

In [ ]:
M = np.arange(10)
M

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.sqrt(M) # raiz cuadrada de cada componente

array([0.    , 1.    , 1.4142, 1.7321, 2.    , 2.2361, 2.4495, 2.6458,
       2.8284, 3.    ])

In [ ]:
np.exp(M.reshape(2,5)) # exponencial de cad componente

array([[   1.    ,    2.7183,    7.3891,   20.0855,   54.5982],
       [ 148.4132,  403.4288, 1096.6332, 2980.958 , 8103.0839]])

Existen funciones universales que actúan sobre dos arrays, ya que realizan operaciones binarias:

In [ ]:
x = np.random.randn(8)
y = np.random.randn(8)
x,y

(array([-0.0119,  1.0048,  1.3272, -0.9193, -1.5491,  0.0222,  0.7584,
        -0.6605]),
 array([ 0.8626, -0.01  ,  0.05  ,  0.6702,  0.853 , -0.9559, -0.0235,
        -2.3042]))

In [ ]:
np.maximum(x, y)

array([ 0.8626,  1.0048,  1.3272,  0.6702,  0.853 ,  0.0222,  0.7584,
       -0.6605])

Existe una numerosa colección de *ufuncs* tanto unarias como bianrias. Se recomienda consultar el manual. 

---
## Expresiones condicionales vectorizadas con *where*

Veamos cómo podemos usar un versión vectorizada de la función `if`. 

Veámoslo con un ejemplo. Supongamos que tenemos dos arrays (unidimensionales) numéricos y otro array booleano del mismo tamaño: 

In [ ]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

Si quisiéramos obtener el array que en cada componente tiene el valor de `xs` si el correspondiente en `cond` es `True`, o el valor de `ys` si el correspondiente en `cond` es `False`, podemos hacer lo siguiente:  

In [ ]:
result = [(x if c else y)
          for x, y, c in zip(xarr, yarr, cond)]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

Sin embargo, esto tiene dos problemas: no es lo suficientemente eficiente, y además no se traslada bien a arrays multidimensionales. Afortunadamente, tenemos `np.where` para hacer esto de manera conveniente:

In [ ]:
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

No necesariamente el segundo y el tercer argumento tiene que ser arrays. Por ejemplo:

In [ ]:
F = np.random.randn(4, 4)

F,np.where(F > 0, 2, -2)

(array([[-0.6525, -1.2183, -1.3326,  1.0746],
        [ 0.7236,  0.69  ,  1.0015, -0.5031],
        [-0.6223, -0.9212, -0.7262,  0.2229],
        [ 0.0513, -1.1577,  0.8167,  0.4336]]),
 array([[-2, -2, -2,  2],
        [ 2,  2,  2, -2],
        [-2, -2, -2,  2],
        [ 2, -2,  2,  2]]))

O una combinación de ambos. Por ejemplos, para modificar sólo las componentes positivas:

In [ ]:
np.where(F > 0, 2, F) 

array([[-0.6525, -1.2183, -1.3326,  2.    ],
       [ 2.    ,  2.    ,  2.    , -0.5031],
       [-0.6223, -0.9212, -0.7262,  2.    ],
       [ 2.    , -1.1577,  2.    ,  2.    ]])

---
## Funciones estadísticas

Algunos métodos para calcular indicadores estadísticos sobre los elementos de un array.

* `np.sum`: suma de los componentes
* `np.mean`: media aritmética
* `np.std` y `np.var`: desviación estándar y varianza, respectivamente.
* `np.max` y `np.min`: máximo y mínimo, resp.
* `np.argmin` y `np.argmax`: índices de los mínimos o máximos elementos, respectivamente.
* `np.cumsum`: sumas acumuladas de cada componente

Estos métodos también se pueden usar como atributos de los arrays. Es decir, por ejemplo `A.sum()` o `A.mean()`.

Veamos algunos ejemplos, generando en primer lugar un array con elementos generados aleatoriamente (siguiendo una distribución normal):

In [ ]:
G = np.random.randn(5, 4)
G

array([[ 1.0107,  1.8249, -0.9975,  0.8506],
       [-0.1316,  0.9124,  0.1882,  2.1695],
       [-0.1149,  2.0037,  0.0296,  0.7953],
       [ 0.1181, -0.7485,  0.585 ,  0.1527],
       [-1.5657, -0.5625, -0.0327, -0.929 ]])

In [ ]:
G.sum()

5.558182835908912

In [ ]:
G.mean()

0.2779091417954456

In [ ]:
G.cumsum() # por defecto, se aplana el array y se hace la suma acumulada

array([1.0107, 2.8356, 1.8381, 2.6887, 2.5571, 3.4695, 3.6577, 5.8272,
       5.7123, 7.716 , 7.7456, 8.5408, 8.6589, 7.9104, 8.4954, 8.6481,
       7.0824, 6.5199, 6.4872, 5.5582])

Todas estas funciones se pueden aplicar a lo largo de un eje, usando el parámetro `axis`. Por ejemplos, para calcular las medias de cada fila (es decir, recorriendo en el sentido de las columnas), aplicamos `mean` por `axis=1`:

In [ ]:
G.mean(axis=1)

array([ 0.6722,  0.7846,  0.6784,  0.0268, -0.7725])

Y la suma de cada columna (es decir, recorriendo las filas), con `sum` por `axis=0`:

In [ ]:
G.sum(axis=0)

array([-0.6833,  3.4299, -0.2274,  3.039 ])

Suma acumulada de cada columna:

In [ ]:
G.cumsum(axis=0)

array([[ 1.0107,  1.8249, -0.9975,  0.8506],
       [ 0.8792,  2.7373, -0.8093,  3.0201],
       [ 0.7642,  4.741 , -0.7797,  3.8153],
       [ 0.8823,  3.9925, -0.1947,  3.968 ],
       [-0.6833,  3.4299, -0.2274,  3.039 ]])

Dentro de cada columna, el número de fila donde se alcanza el mínimo se puede hacer asi:

In [ ]:
G, G.argmin(axis=0)

(array([[ 1.0107,  1.8249, -0.9975,  0.8506],
        [-0.1316,  0.9124,  0.1882,  2.1695],
        [-0.1149,  2.0037,  0.0296,  0.7953],
        [ 0.1181, -0.7485,  0.585 ,  0.1527],
        [-1.5657, -0.5625, -0.0327, -0.929 ]]),
 array([4, 3, 0, 4]))

---
## Métodos para arrays booleanos

In [ ]:
H = np.random.randn(50)
H

array([-0.4826, -0.0363,  1.0954,  0.9809, -0.5895,  1.5817, -0.5287,
        0.457 ,  0.93  , -1.5693, -1.0225, -0.4028,  0.2205, -0.1934,
        0.6692, -1.649 , -2.2528, -1.1668,  0.3536,  0.7021, -0.2746,
       -0.1391,  0.1077, -0.6065, -0.4171, -0.017 , -1.2241, -1.8008,
        1.6347,  0.989 ,  0.4579,  0.5552,  1.3067, -0.4406, -0.3014,
        0.4988, -0.824 ,  1.3206,  0.508 , -0.6534,  0.187 , -0.3917,
       -0.2723, -0.0171,  0.6803,  0.6355, -0.7572,  0.7181, -0.3043,
       -1.6778])

Es bastante frecuente usar `sum` para ontar el número de veces que se cumple una condición en un array, aprovechando que `True` se identifica con 1 y `False` con 0:

In [ ]:
(H > 0).sum() # Number of positive values

22

Las funciones python `any` y `all` tienen también su correspondiente versión vectorizada. `any` se puede ver como un *or* generalizado, y `all`como un *and* generalizado:  

In [ ]:
bools = np.array([False, False, True, False])
bools.any(),bools.all()

(True, False)

Podemos comprobar si se cumple *alguna vez* una condición entre los componentes de un array, o bien si se cumple *siempre* una condición:

In [ ]:
np.any(H > 0)

True

In [ ]:
np.all(H < 10)

True

In [ ]:
np.any(H > 15)

False

In [ ]:
np.all(H > 0)

False

---
## Entrada y salida de arrays en ficheros

Existen una serie de utilidades para guardar el contenido de un array en un fichero y recuperarlo más tarde. 

Las funciones `save` y `load` hacen esto. Los arrays se almacenan en archivos con extensión *npy*.  

In [ ]:
J = np.arange(10)
np.save('un_array', J)

In [ ]:
np.load('un_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Con `savez`, podemos guardar una serie de arrays en un archivo de extensión *npz*, asociados a una serie de claves. Por ejemplo:

In [ ]:
np.savez('array_archivo.npz', a=J, b=J**2)

Cuando hacemos `load` sobre un archivo *npz*, cargamos un objeto de tipo diccionario, con el que podemos acceder (de manera perezosa) a los distintos arrays que se han almacenado:

In [ ]:
arch = np.load('array_archivo.npz')
arch['b']

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
arch['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

En caso de que fuera necesario, podríamos incluso guardar incluso los datos en formato comprimido con `savez_compressed`:

In [ ]:
np.savez_compressed('arrays_comprimidos.npz', a=arr, b=arr)

In [ ]:
!rm un_array.npy
!rm array_archivo.npz
!rm arrays_comprimidos.npz